### ISSUE TITLE
extra volumes aren't connected

### ISSUE THREAD

**Issue by brmzkw** [scaleway/image-fedora#23]
When I create a Fedora image with an extra volume, it is not connected on boot.

```
# cat nbd-client 
# If you don't want to reconfigure this package after installing, uncomment
# the following line:
#AUTO_GEN="n"
# If you don't want the init script to kill nbd-client devices that aren't
# specified in this configuration file, set the following to "false":
KILLALL="false"
# Note that any statical settings in this file will be preserved
# regardless of the setting of AUTO_GEN, so its use is only recommended
# if you set things in a dynamical way (e.g., through a database)
#
NBD_TYPE[0]=f
NBD_DEVICE[0]=/dev/nbd1
NBD_HOST[0]=10.1.38.22
NBD_PORT[0]=4385
```

```
# ps aux | grep -i nbd0
root       285  1.1  0.0   1188    44 ?        S    03:45   0:00 @xnbd-client --blocksize 4096 --retry=900 10.1.38.22 4384 /dev/nbd0
root       286  0.6  0.0      0     0 ?        S<   03:45   0:00 [nbd0]
root       292  0.0  0.0      0     0 ?        S    03:45   0:00 [jbd2/nbd0-8]
root       669  0.0  0.0   4660  2004 pts/0    R+   03:46   0:00 grep --color=auto -i nbd0
```

```
# ps aux | grep -i nbd1
root       671  0.0  0.0   4660  1972 pts/0    S+   03:46   0:00 grep --color=auto -i nbd1
```

**Comment by aimxhaisse** [comment]
What's happening:

- in skeleton-common, we renamed /usr/sbin/oc-add-extra-volumes to /usr/local/sbin/oc-add-extra-volumes
- we have a custom script for Fedora, which was still at /usr/sbin/oc-add-extra-volumes
- since Fedora inherits from skeleton-common, it had 2 versions of the script (/usr/sbin/.. and /usr/local/sbin..)
- the service tried to run the wrong one

I think this issue is fixed by 310655f20612c2a7714d00b13d7c5a74851ba4df

**Comment by moul** [comment]
Nice found

I think we should:
- Replace https://github.com/scaleway/image-tools/blob/master/skeleton-common/usr/local/sbin/oc-add-extra-volumes with https://github.com/scaleway/image-fedora/blob/master/patches/usr/local/sbin/oc-add-extra-volumes (the one on fedora seems to be init-system agnostic unlike the actual image-tools one which seems more upstart-related
- Delete https://github.com/scaleway/image-fedora/tree/master/patches/usr/local/sbin scripts, so the build will use image-tools ones

@aimxhaisse, LGTY ?

**Comment by aimxhaisse** [comment]
Yes, I also think that is the way to go :) we need an unified version of this script across all distribs ; bonus if we can use the xnbd-client from the initrd (we wouldn't need to install nbd in images and deal with different client types/versions/confs/packages/...).

**Comment by moul** [comment]
Let's go for it

**Comment by moul** [comment]
It should be fixed with the latest version Fedora 22 which is using the new initrd, @brmzkw, @aimxhaisse , can you test and confirm it ?

**Comment by moul** [comment]
I'm closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue.

Thank you!
