### ISSUE TITLE
add support for fedora 23

### ISSUE THREAD

**Issue by itamarjp** [scaleway/image-fedora#30]
I would like to run fedora 23 on scaleway, please include this version, thank you.

**Comment by moul** [comment]
Hi @itamarjp, thank you for your feedback,

We are working with the CentOS team to get a new installer for all the Red Hat family (CentOS, Fedora), we will release a Fedora 23 images soon

**Comment by itamarjp** [comment]
Can I help in something  ? 

https://badges.fedoraproject.org/user/itamarjp

**Comment by moul** [comment]
Hi @itamarjp, we will release the CentOS image soon, as soon as it is available, you can try the image to help us find bugs.

As soon as we know the new build system works as expected, we will build Fedora 23

**Comment by moul** [comment]
Here is the detail for what was blocking with CentOS: https://lists.centos.org/pipermail/centos-devel/2016-January/014243.html

**Comment by ausil** [comment]
as the lead fedora release engineer I would like tos ee the official Fedora images coming from the fedora compose process.  what would that take?

**Comment by ausil** [comment]
note that in rpm land the basearch s armhfp, armhf is a debianism and has no meaning outside of debian

**Comment by moul** [comment]
Hi @ausil,

> as the lead fedora release engineer I would like tos ee the official Fedora images coming from the fedora compose process. what would that take?

Nice to meet you, I don't know the "compose process" yet, what kind of output does it produce ?
Is this possible to generate a minimal image for `armhfp` and one for `x86_64` ?

> note that in rpm land the basearch is armhfp, armhf is a debianism and has no meaning outside of debian

No problem for that, I'm used to see `armv7`, `armv7l`, `armhf`, `armhfp`, so the scripts does not take care :)

**Comment by ausil** [comment]
hi @moul,

the normal output of our compsoe process is a xz compressed raw disk image. assuming your u-boot supports the generic distro boot process the image will just boot, assuming that the dtb is upstream.  we do not have a minimal image for x86_64 today but there has been talk about adding one.  you could use the cloud image, however it is configured to use cloud-init for configuration. 

Dennis

**Comment by moul** [comment]
We boot with a network kernel/dtb/initrd, so we don't need any u-boot/dtb/kernel/kernel-modules stuff,

If you have minimal images it's perfect, else I can still clean everything not needed to gain some space (optional).

My first need is not clearly to have something lightweight or not but clearly to have *an x86_64 image as close as possible with the armhf one*.
Do you have links to something, I don't care the format with the same packages ?

**Comment by ausil** [comment]
you can not use a non fedora kernel and call it fedora under the trademark rules. it is also true of most other if not all other distros.  how do you boot the kernel/dtb/initrd?

**Comment by moul** [comment]
Ok,

We can and we will use a fedora kernel, but it can't be packaged within the rootfs as we are attaching the rootfs from inside the initrd

Take a look at the schema here: https://github.com/scaleway/initrd/tree/master/Linux (especially the `start bios` and `start u-boot` blocks)

We have two ways of booting our servers (one for armhf, another one for x86_64), but both of them are downloading the kernel (+dtb for arm) and the initrd using the network from the bootloader;
Then the initrd is responsible for attaching the network drive and perform some user customizations

**Comment by itamarjp** [comment]
moul, I have upgraded my boxes from fedora 22 to fedora 23 and then to fedora 24

**Comment by itamarjp** [comment]
using dnf distro-sync

why you don't just release an fedora 23 and 24 images using the same way you did to create the images for fedora 22 ?

probably there's no single way to create an image that works for all of your different types of machines.

**Comment by itamarjp** [comment]
about trademark start calling it scalewayDora, scalewayEnterpriseLinux, moul's rpm based distro,
or start booting it using a fedora kernel, it will probably  a good idea do try to upstream the changes that can be in fedora side.

**Comment by itamarjp** [comment]
any news about this one ? , lets go to Fedora 25

**Comment by mikioma** [comment]
Any update on this issue? Besides updating Fedora version, it would be nice to have an x86_64 image. So far, only ARM is available...

**Comment by frafra** [comment]
I would really love to see Fedora 25 on Scaleway... :)

**Comment by itamarjp** [comment]
I am interested in having Fedora 27 available, please do something, thank you.

**Comment by halmartin** [comment]
The Fedora 27 image for `VC1` and `C2` instances was released this week.
